# A config override
[config]
outPath="./pack"

[unsup]
enableSigning = true
publicKey = "signify RWRBgYcfobPE7I7STPLaQnp69F06aqQaBSWk0AuUFKlUoCyE6VUZKxJv"
privateKeyFile = "./signingkey.sec"
noGui = false
