author = 'DreamMasterXXL'
name = 'GregTech: New Horizons'
pack-format = 'packwiz:1.1.0'
version = '2.8.1'

[index]
file = 'index.toml'
hash = 'e58c8274bb75021f1ebfb47707ada67305f30afc4055eac1e4491c1b86bafdbf'
hash-format = 'sha256'

[versions]
forge3 = '10.13.4.1614'
minecraft = '1.7.10'
unsup = '1.1.5'