author = 'DreamMasterXXL'
name = 'GregTech: New Horizons'
pack-format = 'packwiz:1.1.0'
version = '2.8.0'

[index]
file = 'index.toml'
hash = '1CC61E403D3EBFCBCEA494739657C72D0B57B2C2824E615DC7547A057B00DBC0'
hash-format = 'sha256'