author = 'DreamMasterXXL'
name = 'GregTech: New Horizons'
pack-format = 'packwiz:1.1.0'
version = '2.8.0'

[index]
file = 'index.toml'
hash = 'c53632ac107bf1070c9636ff222de176cbab572cde66209e792e5d97b8bf033a'
hash-format = 'sha256'