author = "DreamMasterXXL"
name = "GregTech: New Horizons"
pack-format = "packwiz:1.1.0"
version = "2.8.1"

[index]
file = "index.toml"
hash = "87195c1d4e61e8c20ee917e4c9e5f2bc9212d3fc9285a3993a83d13a5005a9b3"
hash-format = "sha256"

[versions]
forge3 = "10.13.4.1614"
minecraft = "1.7.10"
unsup = "1.1.5"