author = 'DreamMasterXXL'
name = 'GregTech: New Horizons'
pack-format = 'packwiz:1.1.0'
version = '2.8.1'

[index]
file = 'index.toml'
hash = 'e58c8274bb75021f1ebfb47707ada67305f30afc4055eac1e4491c1b86bafdbf'
hash-format = 'sha256'