author = 'DreamMasterXXL'
name = 'GregTech: New Horizons'
pack-format = 'packwiz:1.1.0'
version = '2.8.1'

[index]
file = 'index.toml'
hash = '1603b9599531b81c8246f4c0566b090a60eda722d4edc98cab68017d88f25183'
hash-format = 'sha256'

[versions]
forge3 = '10.13.4.1614'
minecraft = '1.7.10'
unsup = '1.1.5'